### ISSUE TITLE
А где же ссылка на log in? )

### ISSUE THREAD

**Issue by homich77** [n1ro0/automarket#3]
https://github.com/n1ro0/automarket/blob/dcc34dd784ee3668b0787d2d5d922d9be7f36957/marketapp/templates/base.html#L26

**Comment by n1ro0** [comment]
Вторая ссылка на логин
          {% else %}
             <lable>Welcome, new user. Please log in. </lable>
                <a href="/signup/">Sign up </a>
                <a href="/signin/"><span class="glyphicon
glyphicon-log-in"></span></a>
            {% endif %}

**Comment by homich77** [comment]
С точки зрения user experience, было бы хорошо слово log in делать ссылкой также
